/// The Dart port against the Python it was ported from.
///
/// `test/fixtures/ptt_reference_vectors.json` is generated by running the ML team's `tera_ptt.py`
/// with **scipy blocked**, so it exercises the same numpy-only path this port targets. If the two
/// disagree, one of them is wrong and this says so before a patient sees a number.
///
/// The tolerances are tight on purpose. These are not "close enough" checks — the two
/// implementations should agree to floating-point noise, and a real divergence shows up as a
/// millisecond, not a rounding bit.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:tera_patient/capture/dsp/tera_ptt.dart';
import 'package:tera_patient/signal/signal_pipeline.dart';

class _Case {
  _Case(Map<String, dynamic> json)
    : name = json['name'] as String,
      fsScg = (json['fs_scg'] as num).toDouble(),
      fsPpg = (json['fs_ppg'] as num).toDouble(),
      scg = (json['scg'] as List).map((v) => (v as num).toDouble()).toList(),
      ppg = (json['ppg'] as List).map((v) => (v as num).toDouble()).toList(),
      expect = json['expect'] as Map<String, dynamic>;

  final String name;
  final double fsScg;
  final double fsPpg;
  final List<double> scg;
  final List<double> ppg;
  final Map<String, dynamic> expect;

  double? expectedDouble(String key) {
    final v = expect[key];
    return v == null ? null : (v as num).toDouble();
  }
}

List<_Case> _loadCases() {
  final file = File('test/fixtures/ptt_reference_vectors.json');
  final raw = jsonDecode(file.readAsStringSync()) as List;
  return raw.map((c) => _Case(c as Map<String, dynamic>)).toList();
}

void main() {
  late List<_Case> cases;

  setUpAll(() {
    cases = _loadCases();
  });

  test('the fixture carries the cases the port is pinned against', () {
    expect(
      cases.map((c) => c.name),
      containsAll(<String>['clean_seated', 'motion_corrupt', 'too_short']),
    );
  });

  group('beat detection matches the reference', () {
    test('SCG beat count and heart rates', () {
      for (final c in cases) {
        final detected = detectScgBeats(c.scg, c.fsScg);

        expect(
          detected.times.length,
          c.expect['n_scg_beats'],
          reason: '${c.name}: SCG beat count',
        );

        final hr = c.expectedDouble('scg_hr');
        if (hr != null) {
          expect(
            detected.peakHr,
            closeTo(hr, 1e-6),
            reason: '${c.name}: SCG peak HR',
          );
        } else {
          expect(
            detected.peakHr.isNaN,
            isTrue,
            reason: '${c.name}: SCG peak HR should be NaN',
          );
        }

        final spec = c.expectedDouble('scg_spectral_hr');
        if (spec != null) {
          expect(
            detected.spectralHr,
            closeTo(spec, 1e-6),
            reason: '${c.name}: SCG spectral HR',
          );
        }
      }
    });

    test('SCG beat times, to the microsecond', () {
      for (final c in cases) {
        final detected = detectScgBeats(c.scg, c.fsScg);
        final expected = (c.expect['scg_times'] as List)
            .map((v) => (v as num).toDouble())
            .toList();

        expect(
          detected.times.length,
          expected.length,
          reason: '${c.name}: beat count',
        );
        for (int i = 0; i < expected.length; i++) {
          expect(
            detected.times[i],
            closeTo(expected[i], 1e-6),
            reason: '${c.name}: SCG beat $i',
          );
        }
      }
    });

    test('PPG foot count and heart rates', () {
      for (final c in cases) {
        final detected = detectPpgFeet(c.ppg, c.fsPpg);

        expect(
          detected.times.length,
          c.expect['n_ppg_feet'],
          reason: '${c.name}: PPG foot count',
        );

        final hr = c.expectedDouble('ppg_hr');
        if (hr != null) {
          expect(
            detected.peakHr,
            closeTo(hr, 1e-6),
            reason: '${c.name}: PPG peak HR',
          );
        }
      }
    });

    test('PPG foot times, to the microsecond', () {
      for (final c in cases) {
        final detected = detectPpgFeet(c.ppg, c.fsPpg);
        final expected = (c.expect['ppg_times'] as List)
            .map((v) => (v as num).toDouble())
            .toList();

        expect(
          detected.times.length,
          expected.length,
          reason: '${c.name}: foot count',
        );
        for (int i = 0; i < expected.length; i++) {
          expect(
            detected.times[i],
            closeTo(expected[i], 1e-6),
            reason: '${c.name}: PPG foot $i',
          );
        }
      }
    });
  });

  group('pairing and summary match the reference', () {
    test('every paired interval', () {
      for (final c in cases) {
        final analysis = analyseCapture(
          scg: c.scg,
          fsScg: c.fsScg,
          ppg: c.ppg,
          fsPpg: c.fsPpg,
          // **The reference's window, not the product's.** The fixtures were generated by the
          // Python at `PTT_MIN_S, PTT_MAX_S = 0.08, 0.40`, so the port is compared against it at
          // those constants — that is what proves the algorithm is the same algorithm. Production
          // runs a wider ceiling by deliberate deviation; see `pttMaxSeconds`.
          pttLoSeconds: 0.08,
          pttHiSeconds: 0.40,
          // The Python does not trim before summarising, so neither does the comparison.
          trimOutliers: false,
        );
        final expected = (c.expect['ptt_ms'] as List)
            .map((v) => (v as num).toDouble())
            .toList();

        expect(
          analysis.pttMs.length,
          expected.length,
          reason: '${c.name}: paired count',
        );
        for (int i = 0; i < expected.length; i++) {
          expect(
            analysis.pttMs[i],
            closeTo(expected[i], 1e-6),
            reason: '${c.name}: interval $i',
          );
        }
      }
    });

    test('median, sd, IQR and pair yield', () {
      for (final c in cases) {
        final analysis = analyseCapture(
          scg: c.scg,
          fsScg: c.fsScg,
          ppg: c.ppg,
          fsPpg: c.fsPpg,
          // **The reference's window, not the product's.** The fixtures were generated by the
          // Python at `PTT_MIN_S, PTT_MAX_S = 0.08, 0.40`, so the port is compared against it at
          // those constants — that is what proves the algorithm is the same algorithm. Production
          // runs a wider ceiling by deliberate deviation; see `pttMaxSeconds`.
          pttLoSeconds: 0.08,
          pttHiSeconds: 0.40,
          // The Python does not trim before summarising, so neither does the comparison.
          trimOutliers: false,
        );
        final s = analysis.summary;

        expect(s.n, c.expect['n_paired'], reason: '${c.name}: n');

        for (final field in <(String, double)>[
          ('ptt_median_ms', s.median),
          ('ptt_sd_ms', s.sd),
          ('ptt_iqr_ms', s.iqr),
          ('pair_yield', s.pairYield),
        ]) {
          final (key, actual) = field;
          final want = c.expectedDouble(key);
          if (want == null) {
            expect(
              actual.isNaN,
              isTrue,
              reason: '${c.name}: $key should be NaN',
            );
          } else {
            expect(actual, closeTo(want, 1e-6), reason: '${c.name}: $key');
          }
        }
      }
    });
  });

  group('the quality gate reaches the same verdict', () {
    test('accept or refuse, case by case', () {
      for (final c in cases) {
        final analysis = analyseCapture(
          scg: c.scg,
          fsScg: c.fsScg,
          ppg: c.ppg,
          fsPpg: c.fsPpg,
          // **The reference's window, not the product's.** The fixtures were generated by the
          // Python at `PTT_MIN_S, PTT_MAX_S = 0.08, 0.40`, so the port is compared against it at
          // those constants — that is what proves the algorithm is the same algorithm. Production
          // runs a wider ceiling by deliberate deviation; see `pttMaxSeconds`.
          pttLoSeconds: 0.08,
          pttHiSeconds: 0.40,
          // The Python does not trim before summarising, so neither does the comparison.
          trimOutliers: false,
        );

        expect(
          analysis.gate.passed,
          c.expect['gate_ok'],
          reason:
              '${c.name}: gate verdict — reference said "${c.expect['gate_reason']}", '
              'port said "${analysis.gate.detail ?? 'ok'}"',
        );
      }
    });

    test('a clean seated capture is accepted with a tight spread', () {
      final c = cases.firstWhere((c) => c.name == 'clean_seated');
      final analysis = analyseCapture(
        scg: c.scg,
        fsScg: c.fsScg,
        ppg: c.ppg,
        fsPpg: c.fsPpg,
        pttLoSeconds: 0.08,
        pttHiSeconds: 0.40,
        trimOutliers: false,
      );

      expect(analysis.gate.passed, isTrue);
      expect(analysis.summary.sd, lessThan(maxPttSdMs));
      expect(analysis.summary.n, greaterThanOrEqualTo(minPairs));
    });

    test('motion is refused by the cross-sensor check', () {
      // The check a single-sensor product cannot run: chest and finger disagreeing about the
      // heart rate means they are not seeing the same heartbeats.
      final c = cases.firstWhere((c) => c.name == 'motion_corrupt');
      final analysis = analyseCapture(
        scg: c.scg,
        fsScg: c.fsScg,
        ppg: c.ppg,
        fsPpg: c.fsPpg,
        pttLoSeconds: 0.08,
        pttHiSeconds: 0.40,
        trimOutliers: false,
      );

      expect(analysis.gate.passed, isFalse);
      expect(analysis.gate.failure, GateFailure.sensorsDisagree);
    });

    test('a capture shorter than three seconds yields nothing', () {
      final c = cases.firstWhere((c) => c.name == 'too_short');
      final analysis = analyseCapture(
        scg: c.scg,
        fsScg: c.fsScg,
        ppg: c.ppg,
        fsPpg: c.fsPpg,
        pttLoSeconds: 0.08,
        pttHiSeconds: 0.40,
        trimOutliers: false,
      );

      expect(analysis.gate.passed, isFalse);
      expect(analysis.gate.failure, GateFailure.insufficientBeats);
      expect(analysis.pttMs, isEmpty);
    });
  });

  group('the tunables are the ML team validated figures', () {
    test('nothing has been retuned in the port', () {
      // Changing a number here silently changes what the product accepts. They come from
      // tera_ptt.py and the proposal's 10 ms sensing budget.
      expect(pttMinSeconds, 0.08);
      expect(minPairs, 12);
      expect(minPairYield, 0.50);
      expect(scgOnsetFrac, 0.82);
    });

    test('the dispersion ceiling is a recorded deviation, and the loosest one', () {
      // **The reference's 10 ms is the one figure in this file that was independently validated.**
      // It is the proposal's sensing-chain budget, and on the PhysioNet PTT dataset's seated
      // condition it keeps 6 recordings of 8 — so "unreachable outside a lab" is not what the
      // reference measured. Its own comment says the seated recordings it rejects, at SD up to
      // 87 ms, "should be refused".
      //
      // We run 45 anyway, on product instruction, to get a first end-to-end capture through
      // consumer hardware that the reference never saw: a 30 fps camera and a phone accelerometer.
      // Frame quantisation and respiratory modulation together account for roughly 15-25 ms of it,
      // not 45, so this is a deliberate over-allowance and is the first number to revisit.
      //
      // Asserted separately from "nothing has been retuned" because it *is* a retune, and burying
      // it under that heading is how the two flat HR constants survived for weeks.
      expect(maxPttSdMs, 45.0);

      // The clinically meaningful PTT change is 10 ms. This ceiling is four and a half times it,
      // which is the sentence that matters and the reason this test exists.
      expect(maxPttSdMs / 10.0, greaterThan(4));
    });

    test('outliers are trimmed before the spread is judged', () {
      // The gate was deciding on untrimmed pairs while the backend has always trimmed with the
      // same fence, so the handset refused sessions on a statistic the server would never use.
      expect(iqrFenceMultiplier, 1.5);

      // Two mispaired intervals in a coherent run must not set the verdict.
      final coherent = [for (int i = 0; i < 40; i++) 238.0 + (i % 5)];
      final withOutliers = [...coherent, 95.0, 470.0];

      final rawSd = summarise(withOutliers, 42).sd;
      final trimmedSd = summarise(tukeyTrim(withOutliers), 42).sd;

      expect(rawSd, greaterThan(30));
      expect(trimmedSd, lessThan(5));
      expect(tukeyTrim(withOutliers).length, 40);
    });

    test('trimming cannot empty the set or fire on a short one', () {
      // Both guards mirror the backend's `trimmed_session_ptt`.
      expect(tukeyTrim(const [240.0, 241.0, 242.0]).length, 3);
      final identical = List<double>.filled(20, 240.0);
      expect(tukeyTrim(identical).length, 20);
    });

    test('the pairing ceiling is a recorded deviation, not a drift', () {
      // The reference and BUILD_SPEC 4.4 both say 0.40. We run 0.50, because our AO mark is
      // backtracked toward the envelope onset and our PPG foot is placed by intersecting tangents
      // — both corrections are right, and both lengthen the measured interval relative to the
      // textbook figure this bound was written for.
      //
      // Asserted rather than left implicit so the next person sees a decision instead of a
      // discrepancy, and so a further drift has to be argued for. The floor is unchanged: raising
      // it would discard pairs, which is the opposite of what a low pair count needs.
      expect(pttMaxSeconds, 0.50);
      expect(pttMinSeconds, 0.08);
    });

    test(
      'the cross-sensor floor is relaxed, and the within-sensor floor is not',
      () {
        // The dual-estimator floor is the net that catches harmonic double-counting. Widening it
        // would let a partially-fooled capture through, so it stays at EC13's 5 bpm while the
        // cross-sensor comparison gets the consumer-hardware floor.
        expect(ec13FloorBpm, 5.0);
        expect(crossSensorFloorBpm, 10.0);
        expect(hrToleranceBpm(60), closeTo(6.0, 1e-9));
        expect(crossSensorToleranceBpm(60), 10.0);

        // The relative term is untouched, so above 100 bpm the two agree again.
        expect(crossSensorToleranceBpm(130), closeTo(13.0, 1e-9));
        expect(hrToleranceBpm(130), closeTo(13.0, 1e-9));
      },
    );

    test('the pipeline never refuses a capture its own gate accepted', () {
      // **The defect this pins.** `minUsableBeats` was 30 while `minPairs` — the reference's
      // `MIN_PAIRS`, and the figure `qualityGate` actually applies — was 12. A capture with 12 to
      // 29 paired beats therefore passed the signal chain and was then thrown away one branch
      // later as `insufficient_beats`, so the patient was asked to repeat a minute the chain had
      // already accepted.
      //
      // Stated as an inequality rather than an equality because the two count slightly different
      // things: `minPairs` bounds paired beats, `minUsableBeats` bounds intervals surviving the
      // plausibility window. A second gate is allowed to exist; it is not allowed to be stricter
      // than the first without someone deciding that on purpose.
      expect(minUsableBeats, lessThanOrEqualTo(minPairs));
    });

    test('the HR tolerance is EC13, not a flat number', () {
      // **This assertion previously read `expect(hrTolBpm, 10.0)` and `expect(crossHrTolBpm, 8.0)`
      // under the heading "nothing has been retuned in the port".** Both were retunes. The
      // reference has no flat tolerance anywhere; it has `hr_tolerance_bpm(hr)`, and the test was
      // holding the port to the divergence instead of to the source.
      expect(ec13Relative, 0.10);
      expect(ec13FloorBpm, 5.0);

      // Ten percent of the rate, or five bpm, whichever is greater.
      expect(hrToleranceBpm(40), 5.0, reason: 'floor applies below 50 bpm');
      expect(hrToleranceBpm(50), 5.0, reason: 'floor and relative meet here');
      expect(hrToleranceBpm(60), closeTo(6.0, 1e-9));
      expect(hrToleranceBpm(100), closeTo(10.0, 1e-9));
      expect(hrToleranceBpm(130), closeTo(13.0, 1e-9));
    });

    test('a rate the chain could not estimate falls back to the floor', () {
      // Never zero, and never infinite: a tolerance of zero refuses everything and a tolerance of
      // infinity accepts everything, and both are reachable from a division on an empty capture.
      expect(hrToleranceBpm(double.nan), ec13FloorBpm);
      expect(hrToleranceBpm(0), ec13FloorBpm);
      expect(hrToleranceBpm(-30), ec13FloorBpm);
      expect(hrToleranceBpm(double.infinity), isNot(0));
    });

    test('the old constants were stricter than the reference where it matters', () {
      // The failure this fixes, stated as arithmetic. An elevated heart rate is the state of a
      // nervous person taking a first reading, and the old cross-sensor constant was tightest
      // exactly there — refusing captures the reference accepts and reporting them as noise.
      const oldFlatCross = 8.0;
      expect(hrToleranceBpm(100), greaterThan(oldFlatCross));
      expect(hrToleranceBpm(130), greaterThan(oldFlatCross));

      const oldFlatDual = 10.0;
      expect(hrToleranceBpm(130), greaterThan(oldFlatDual));

      // And too lax at a resting rate, which is the same defect in the other direction.
      expect(hrToleranceBpm(60), lessThan(oldFlatDual));
    });
  });
}
