/// The Tera signal chain, ported from the ML team's `tera_ptt.py`.
///
///     SCG (accelerometer, chest)  -+
///                                  +-> beat pairing -> per-beat PTT -> quality gate
///     PPG (camera + torch, finger)-+
///
/// # Why this is Dart and not a server call
///
/// The ML team's reference runs in Python on a backend and takes raw sample arrays. Invariant 2
/// says raw waveform never leaves the handset, and that is a regulatory claim in the pitch, not a
/// preference. So the chain runs here, the raw arrays stay on the phone, and only per-beat
/// intervals and quality figures are submitted.
///
/// # Fidelity
///
/// Ported from the reference's **scipy-free fallback path**, which it ships for exactly this
/// case: an FFT brick-wall band-pass, an FFT Hilbert transform, and a simple peak finder. That
/// path is reproducible in Dart exactly; a Butterworth `sosfiltfilt` chain would not have been.
/// `test/ptt_reference_test.dart` checks this implementation against vectors generated by the
/// Python with scipy disabled.
///
/// PTT **shortens** as blood pressure **rises** (Moens-Korteweg). A sign error here is silent and
/// catastrophic, so the direction is asserted in the tests, as it is in the reference.
library;

import 'dart:math' as math;

import 'package:meta/meta.dart';

import 'signal_ops.dart';

// ------------------------------------------------------------------- tunables
//
// Reproduced from `tera_ptt.py`. These are the ML team's validated figures and are not to be
// retuned here: `MAX_PTT_SD_MS` in particular is the proposal's 10 ms sensing-chain budget, and
// on the PhysioNet PTT dataset it keeps 6 of 8 seated recordings and rejects 13 of 16 walking or
// running ones. Changing a number in this block silently changes what the product accepts.

/// Physiological acceptance window for a single transit time, seconds.
///
/// **The ceiling is 0.50, not the reference's and BUILD_SPEC 4.4's 0.40.** A recorded deviation,
/// and the reason is the fiducials at either end rather than the physiology between them: our AO
/// mark is backtracked to [scgOnsetFrac] of the envelope rise, which places it *earlier* than the
/// envelope peak, and the PPG foot is located by intersecting tangents, which places it earlier
/// than the argmin. Both corrections are right and both lengthen the measured interval, so the
/// number this window bounds is systematically larger than the textbook AO-to-foot figure it was
/// written for.
///
/// The floor stays at 0.08. Raising it to 0.10 was considered and rejected: it discards pairs
/// rather than admitting them, which is the opposite of what a low pair count needs, and a
/// transit time near 0.08 s is reachable in a stiff artery over a short arm.
///
/// **What makes widening safe is what happens downstream, not this bound.** At 60 bpm a cardiac
/// cycle is 1000 ms, so 500 ms still cannot reach the next cycle's foot — a missed beat does not
/// become a wrong pair, it stays unpaired. And a run that mixes true pairs with spurious ones
/// scatters by hundreds of milliseconds, which [maxPttSdMs] refuses at 10 ms. The dispersion
/// ceiling is the real guard; this window only decides what is offered to it.
const double pttMinSeconds = 0.08;
const double pttMaxSeconds = 0.50;

/// ANSI/AAMI EC13 readout tolerance: ten percent of the rate, or five bpm, whichever is greater.
///
/// **This replaces two flat constants — 10 bpm dual-estimator and 8 bpm cross-sensor — and the
/// difference is not cosmetic.** EC13 scales with heart rate because a counting error scales with
/// heart rate: at 60 bpm a 10 bpm disagreement is a sixth of the signal, at 130 bpm it is well
/// inside one beat's worth of edge placement. A flat number is therefore wrong in both directions
/// at once, and the port had one:
///
/// | HR | EC13 | old flat dual | old flat cross |
/// |----|------|---------------|----------------|
/// | 60 | 6 | 10 (too lax) | 8 (too lax) |
/// | 80 | 8 | 10 | 8 |
/// | 100 | 10 | 10 | 8 (too strict) |
/// | 130 | 13 | 10 (too strict) | 8 (too strict) |
///
/// The cross-sensor constant was the worse of the two: stricter than the reference at every rate
/// above 80 bpm. An elevated heart rate is the state of a nervous person taking their first
/// reading, and of much of the population this product exists for — so the gate was tightest
/// exactly where it should have been loosest, and refused captures the ML reference accepts.
///
/// Applying a single-device readout spec to the agreement between two of our own estimates is the
/// conservative reading, and the reference says so: if each estimator is independently allowed E,
/// their difference could reach 2E, and this demands E.
const double ec13Relative = 0.10;
const double ec13FloorBpm = 5.0;

double hrToleranceBpm(double hrBpm) {
  if (!hrBpm.isFinite || hrBpm <= 0) return ec13FloorBpm;
  return math.max(ec13Relative * hrBpm, ec13FloorBpm);
}

/// Floor for the **cross-sensor** comparison only, bpm. A deliberate departure from EC13's 5.
///
/// The failure that prompted it, from a real seated capture:
///
///     chest 60.3 bpm vs finger 54.2 bpm = 6.1 bpm apart, EC13 limit 5.4 bpm
///
/// EC13's floor is a *readout* tolerance for one device against a reference. Applying it to two of
/// our own estimators was described in the reference as the conservative reading, and within one
/// sensor it still is — [hrToleranceBpm] keeps the 5 bpm floor for the dual-estimator check, which
/// is the net that catches harmonic double-counting and must not be widened.
///
/// Across two sensors it is asking for something different: that a phone camera watching a
/// fingertip through skin and a phone accelerometer resting on a sternum count the same number of
/// beats to within five. They are measuring different physical quantities through different tissue
/// with a fifteen-fold difference in sample rate, and the camera's is the one that loses beats —
/// a fingertip that relaxes slightly mid-capture shallows the pulse below the detector's
/// prominence floor for a stretch.
///
/// **What is given up, plainly.** At rest this now admits a chest-finger gap of up to 10 bpm, and
/// a gap that size does mean the two are not counting identically. The check that still refuses
/// such a capture is [maxPttSdMs]: pairs formed between streams that have drifted apart scatter
/// far beyond a 10 ms dispersion ceiling. The cross-sensor rate comparison is a cheap proxy for
/// simultaneity; the dispersion of the intervals it produces is the direct measurement, and that
/// one is untouched.
const double crossSensorFloorBpm = 10.0;

/// EC13's relative term with the consumer-hardware floor. See [crossSensorFloorBpm].
double crossSensorToleranceBpm(double hrBpm) {
  if (!hrBpm.isFinite || hrBpm <= 0) return crossSensorFloorBpm;
  return math.max(ec13Relative * hrBpm, crossSensorFloorBpm);
}

/// Paired beats needed before a median means anything.
const int minPairs = 12;

/// Fraction of detected SCG beats that must find a partner.
const double minPairYield = 0.50;

/// Within-session dispersion ceiling, milliseconds, applied to the **trimmed** intervals.
///
/// **45, not the reference's 10, and this is the loosest thing in the chain. Read the whole note
/// before moving it again.**
///
/// The reference's 10 ms is not a taste: it is the proposal's sensing-chain budget (SCG 0.57 ms
/// plus PPG 4-7 ms against a 10-50 ms signal), and it was validated — on the PhysioNet PTT
/// dataset's seated condition it keeps 6 recordings of 8 and rejects 13 of 16 walking or running
/// ones. Its own comment says the two seated recordings it rejects "are genuinely noisy (SD up to
/// 87 ms) and should be refused".
///
/// So the claim that 10 ms is unreachable outside a lab is not what the reference measured; three
/// quarters of its seated recordings reached it. What those recordings did not have is a 30 fps
/// camera and a consumer accelerometer. Two costs are ours and not theirs:
///
///   * **Frame quantisation.** One frame at 30 fps is 33 ms. Intersecting tangents place the foot
///     sub-sample, which is why this is not simply hopeless, but the residual is several ms and it
///     is irreducible without a faster camera.
///   * **Respiratory modulation.** Intrathoracic pressure swings with breathing and moves transit
///     time beat to beat. Real, and smaller than it is usually quoted — on the order of 5-15 ms
///     peak to peak for pulse arrival time, not 20-40 ms of standard deviation.
///
/// Those add up to roughly 15-25 ms, not 45. **45 is a deliberate over-allowance, taken on product
/// instruction to get a first end-to-end capture through, and it is the number to revisit first
/// once there is more than one recording to look at.**
///
/// What it costs, stated so nobody has to rediscover it: `TREND_MIN_DELTA_MS` — the smallest PTT
/// change this product calls clinically meaningful — is 10 ms. A session admitted at 45 ms of
/// internal dispersion carries a median whose standard error over 60 pairs is around 7 ms, which
/// is the same order as the effect being measured. Such a session is weak evidence of a direction,
/// not a measurement, and the confidence score is what has to carry that: `snr_db` here is
/// `20*log10(median/sd)`, so 10 ms scores 27.6 dB and 45 ms scores 14.5 dB against the backend's
/// 20 dB confidence ceiling. The degradation is real but it is gentle, and it does not fully
/// absorb a four-fold rise in dispersion.
///
/// **This is now the only limb of the gate that has not been loosened**, and the previous two
/// relaxations — the cross-sensor floor and the pairing ceiling — were each argued as safe
/// *because* this one held at 10. That argument no longer applies. Nothing downstream re-checks
/// dispersion: there is no server-side SD ceiling.
const double maxPttSdMs = 45.0;

/// Tukey fence multiplier for outlier rejection, matching the backend's `iqr_fence_multiplier`.
const double iqrFenceMultiplier = 1.5;

/// Envelope fraction marking aortic valve opening. Swept, not guessed: 0.20 overshoots to -25 ms
/// and the envelope peak itself is +18 ms.
const double scgOnsetFrac = 0.82;

/// Beats faster than this are not beats.
const int maxBpm = 200;

/// Physiologically plausible seated heart rate, bpm. The reference's `HR_PLAUSIBLE["seated"]`.
///
/// **Present in `tera_ptt.py` and missing from this port until a real capture needed it.** The
/// reference applies it in `hr_gate`, which decides whether a *rate* may be reported; it is applied
/// here, in the PTT gate, as well.
///
/// The case that forced it: the dual-estimator check compares peak detection against spectral
/// estimation on the assumption that two independent methods do not fail the same way. Usually
/// true. But a chest whose diastolic complex nearly matches its systolic one puts so much energy at
/// the harmonic that *both* estimators lock onto it — and then they agree, within EC13, on a rate
/// that is wrong by a factor of two or three. The check passes and the capture is accepted with a
/// heart rate of 187 bpm for a patient sitting still at 58.
///
/// Agreement between two fooled estimators is not evidence. A window is, because it is a fact about
/// people rather than about either method: nobody produces 187 bpm sitting quietly in a chair, and
/// a capture claiming they did is describing its own detector. Invariant 7 — where the signal is
/// ambiguous, refuse rather than report.
///
/// `maxBpm` does not cover this. It is 200, the fastest a heart can go at all, and is the
/// refractory period's input; this is the range a *seated resting* capture may occupy.
const double hrPlausibleMinBpm = 45.0;
const double hrPlausibleMaxBpm = 140.0;

// --------------------------------------------------------- harmonic suppression
//
// **The first real captures failed here, on every axis, and the numbers name the cause:**
//
//     peak 119.2 bpm vs spectral 58.0 bpm = 61.2 bpm apart
//
// 119.2 / 58.0 = 2.06. The time-domain detector was counting the chest wall twice per cardiac
// cycle — aortic *opening* and aortic *closing*, the "lub" and the "dub" — while the spectral
// estimator correctly locked onto the fundamental. Both events produce a genuine bump in the
// Hilbert envelope with a real trough between them, so no amount of prominence tuning separates
// them: they are both real, and only one of them is the beat.
//
// **The refractory period the reference already has cannot fix this, and it is worth being precise
// about why.** `find_peaks(distance=int(fs * 60 / max_bpm))` with `max_bpm = 200` is a 300 ms
// floor, and it is already in force — at the 468 Hz this handset achieved, that is 140 samples.
// But the spurious peaks sat 503 ms apart (119.2 bpm), comfortably *outside* 300 ms. A refractory
// derived from the fastest heart a human can have says nothing useful about a heart beating at 58.
// The systolic ejection period at rest is 300-400 ms, so the aortic-closing bump lands just past
// a floor built for 200 bpm. The floor is not too small by a little; it is answering a different
// question.
//
// So the second pass derives its refractory from the fundamental the spectral estimator found,
// which is the only estimate available that is immune to this failure — a harmonic adds energy at
// 2f, it does not move the peak at f.

/// Fraction of the spectral fundamental period used as the refractory period on the second pass.
///
/// Three quarters of a beat: wide enough to swallow a diastolic bump at any physiological systolic
/// ejection period, narrow enough that genuine beat-to-beat variation — which at rest is a few
/// percent of the interval, not a quarter of it — still resolves.
const double harmonicRefractoryFraction = 0.75;

/// How far above the spectral fundamental the peak rate must sit before a second pass is tried.
///
/// Halfway to a doubling. A detector genuinely running 50% fast against the fundamental is not
/// making a small counting error, and the honest readings this must not disturb sit within EC13 of
/// the fundamental — a few percent, nowhere near this.
const double harmonicSuspicionRatio = 1.5;

@immutable
class BeatDetection {
  const BeatDetection({
    required this.times,
    required this.peakHr,
    required this.spectralHr,
    this.harmonicSuppressed = false,
  });

  /// Event times in seconds from the start of the capture.
  final List<double> times;

  /// Heart rate from the median interval between detected events.
  final double peakHr;

  /// Independent heart rate from the dominant envelope frequency.
  final double spectralHr;

  /// True when the second pass ran and its result was adopted.
  ///
  /// Reported rather than silent: a capture that needed harmonic suppression is a capture whose
  /// diastolic complex is as strong as its systolic one, which is a fact about how the phone sat
  /// on the sternum and is worth seeing in a log before it is worth hiding in a median.
  final bool harmonicSuppressed;

  static const empty = BeatDetection(
    times: [],
    peakHr: double.nan,
    spectralHr: double.nan,
  );
}

/// Heart rate implied by a run of peak *indices*, in bpm.
///
/// Same plausibility window as [_hrFromTimes], applied to sample gaps rather than to the
/// backtracked event times. Used only to decide whether a second pass helped: the two differ by
/// the backtrack, which shifts every peak by roughly the same amount and so leaves the intervals —
/// and therefore the rate — alone.
double _hrFromPeakIndices(List<int> peaks, double fs) {
  final rr = <double>[
    for (int i = 1; i < peaks.length; i++)
      if ((peaks[i] - peaks[i - 1]) / fs > 60.0 / maxBpm &&
          (peaks[i] - peaks[i - 1]) / fs < 60.0 / 40.0)
        (peaks[i] - peaks[i - 1]) / fs,
  ];
  if (rr.isEmpty) return double.nan;
  return 60.0 / median(rr);
}

/// Peak detection, with a second pass when the first looks like it counted harmonics.
///
/// Pass one is the reference's, unchanged, and is what almost every capture will use. Pass two
/// only runs when the rate it produced is at least [harmonicSuspicionRatio] times the spectral
/// fundamental, and **its result is adopted only if it agrees with that fundamental better than
/// pass one did.** A wider refractory that makes the disagreement worse is not a correction, and
/// is discarded.
///
/// # What this costs, stated plainly
///
/// The dual-estimator check compares the peak rate against the spectral rate, and its value is
/// that the two are arrived at independently. On a capture where pass two fires, they no longer
/// are: the spectral estimate has constrained the peak search. That limb of the gate is weaker for
/// those captures and it would be dishonest to pretend otherwise.
///
/// Two things keep it from being decorative. The constraint only ever *removes* peaks, so it
/// cannot manufacture a beat train from a recording that has none — a signal with no rhythm still
/// fails, because a wider refractory on noise does not produce a regular series. And the
/// cross-sensor check is untouched: chest rate against finger rate, two different sensors reading
/// two different physical quantities, which `quality_gate` already calls the strongest check it
/// has. That limb remains fully independent, and a capture that passes the gate still had to
/// satisfy it.
({List<int> peaks, bool suppressed}) _detectPeaks({
  required List<double> trace,
  required double fs,
  required double prominence,
  required double spectralHrBpm,
}) {
  final baseDistance = (fs * 60 / maxBpm).toInt();
  final first = findPeaks(
    trace,
    distance: baseDistance,
    prominence: prominence,
  );

  if (!spectralHrBpm.isFinite || spectralHrBpm <= 0) {
    return (peaks: first, suppressed: false);
  }
  final firstHr = _hrFromPeakIndices(first, fs);
  if (!firstHr.isFinite || firstHr < spectralHrBpm * harmonicSuspicionRatio) {
    return (peaks: first, suppressed: false);
  }

  // Never narrower than the reference's floor: this pass exists to widen.
  final widened = math.max(
    baseDistance,
    (harmonicRefractoryFraction * fs * 60.0 / spectralHrBpm).round(),
  );
  final second = findPeaks(trace, distance: widened, prominence: prominence);
  final secondHr = _hrFromPeakIndices(second, fs);
  if (!secondHr.isFinite) return (peaks: first, suppressed: false);

  if ((secondHr - spectralHrBpm).abs() >= (firstHr - spectralHrBpm).abs()) {
    return (peaks: first, suppressed: false);
  }
  return (peaks: second, suppressed: true);
}

/// Aortic-opening times from chest SCG.
///
/// The envelope *peak* sits inside the ejection complex and the smoothing kernel pushes it later
/// still, so each peak is backtracked to [scgOnsetFrac] of its rise, with linear interpolation
/// between the straddling samples — at 200 Hz one sample is 5 ms, a large slice of a 10-50 ms
/// signal.
BeatDetection detectScgBeats(List<double> scg, double fs) {
  final env = envelope(scg, fs, 1.0, 25.0);
  if (env.length < fs * 3) return BeatDetection.empty;

  // The spectral estimate is computed first here, because the second pass needs it. It reads the
  // envelope's dominant frequency and is unaffected by the double-counting: a harmonic puts energy
  // at 2f, it does not move the peak at f.
  final spectral = spectralHr(env, fs);
  final detected = _detectPeaks(
    trace: env,
    fs: fs,
    prominence: 0.5 * std(env),
    spectralHrBpm: spectral,
  );
  final peaks = detected.peaks;

  final onsets = <double>[];
  final back = (0.12 * fs).toInt();
  for (final p in peaks) {
    final a = math.max(0, p - back);
    final seg = env.sublist(a, p + 1);
    if (seg.length < 2) {
      onsets.add(p.toDouble());
      continue;
    }
    final base = seg.reduce(math.min);
    final thr = base + scgOnsetFrac * (env[p] - base);
    int? firstAbove;
    for (int i = 0; i < seg.length; i++) {
      if (seg[i] >= thr) {
        firstAbove = i;
        break;
      }
    }
    if (firstAbove == null) {
      onsets.add(p.toDouble());
      continue;
    }
    double i = firstAbove.toDouble();
    if (firstAbove > 0 && seg[firstAbove] > seg[firstAbove - 1]) {
      i =
          (firstAbove - 1) +
          (thr - seg[firstAbove - 1]) / (seg[firstAbove] - seg[firstAbove - 1]);
    }
    onsets.add(a + i);
  }

  final times = uniqueRounded(onsets.map((o) => o / fs).toList(), 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectral,
    harmonicSuppressed: detected.suppressed,
  );
}

/// A real PPG has a fast systolic upstroke and a slow decay, so its *derivative* is positively
/// skewed. Phone cameras often deliver it inverted, because more blood absorbs more light.
///
/// Testing the skew of the amplitude is the wrong test and gives the wrong answer. Testing the
/// skew of the derivative is the right one. The reference notes this cost a debugging session;
/// do not "simplify" it back.
List<double> orientPpg(List<double> x) {
  final d = gradient(x);
  final dm = mean(d);
  final ds = std(d);
  double acc = 0;
  for (final v in d) {
    acc += math.pow(v - dm, 3).toDouble();
  }
  final skew = (acc / d.length) / (math.pow(ds, 3) + 1e-12);
  return skew < 0 ? x.map((v) => -v).toList() : List<double>.from(x);
}

/// Pulse-foot times at the fingertip.
///
/// **Intersecting tangents, not argmin.** At 30 fps one sample is 33 ms and the foot is a flat
/// minimum, so argmin lands a sample or two early — measured at -39 ms. Intersecting the
/// diastolic baseline with the tangent at maximum upstroke is sub-sample accurate, and is the
/// standard fiducial in the PTT literature.
BeatDetection detectPpgFeet(List<double> ppg, double fs) {
  final x = orientPpg(ppg);
  final f = bandpass(x, fs, 0.5, math.min(8.0, 0.45 * fs));
  if (f.length < fs * 3) return BeatDetection.empty;

  // **The same correction on the finger, and it is not optional here either.** A PPG has a
  // dicrotic notch — the aortic valve closing, seen downstream — which is the same event that
  // doubles the chest count, arriving by a different route. Correcting only one stream would leave
  // the two rates disagreeing and fail the cross-sensor check instead, which is the same refusal
  // wearing a different reason.
  final spectral = spectralHr(hilbertEnvelope(f), fs);
  final detected = _detectPeaks(
    trace: f,
    fs: fs,
    prominence: 0.3 * std(f),
    spectralHrBpm: spectral,
  );
  final peaks = detected.peaks;
  if (peaks.length < 3) return BeatDetection.empty;

  final gaps = <double>[
    for (int i = 1; i < peaks.length; i++) (peaks[i] - peaks[i - 1]).toDouble(),
  ];
  final ibi = median(gaps);
  final win = math.min(0.25 * ibi, 0.20 * fs).toInt();

  final d = gradient(f);
  final feet = <double>[];
  for (final p in peaks) {
    final a = math.max(0, p - win);
    if (p - a < 3) continue;
    final seg = f.sublist(a, p + 1);
    final dseg = d.sublist(a, p + 1);

    int iMin = 0;
    for (int i = 1; i < seg.length; i++) {
      if (seg[i] < seg[iMin]) iMin = i;
    }
    if (p - (a + iMin) < 2) continue;

    int iSlope = iMin;
    for (int i = iMin; i < dseg.length; i++) {
      if (dseg[i] > dseg[iSlope]) iSlope = i;
    }
    final slope = dseg[iSlope];
    if (slope <= 1e-12) {
      feet.add((a + iMin) / fs);
      continue;
    }
    // baseline y = seg[iMin]; tangent y = seg[iSlope] + slope * (i - iSlope)
    double iFoot = iSlope + (seg[iMin] - seg[iSlope]) / slope;
    iFoot = iFoot.clamp(0, (p - a).toDouble());
    feet.add((a + iFoot) / fs);
  }

  final times = uniqueRounded(feet, 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectral,
    harmonicSuppressed: detected.suppressed,
  );
}

double _hrFromTimes(List<double> times) {
  final rr = <double>[
    for (int i = 1; i < times.length; i++)
      if (times[i] - times[i - 1] > 60.0 / maxBpm &&
          times[i] - times[i - 1] < 60.0 / 40.0)
        times[i] - times[i - 1],
  ];
  if (rr.isEmpty) return double.nan;
  return 60.0 / median(rr);
}

/// Match each SCG beat to the first unclaimed PPG foot inside the PTT window.
///
/// PTT is defined between two events of **the same cardiac cycle**. Pairing a beat with a foot
/// from a different cycle does not degrade the number, it invents one. So an unmatched beat is
/// dropped, never stretched to fit.
List<double> pairBeats(
  List<double> scgTimes,
  List<double> ppgTimes, {
  double lo = pttMinSeconds,
  double hi = pttMaxSeconds,
}) {
  if (scgTimes.isEmpty || ppgTimes.isEmpty) return const [];
  final used = <int>{};
  final ptt = <double>[];
  for (final ts in scgTimes) {
    for (int i = 0; i < ppgTimes.length; i++) {
      if (used.contains(i)) continue;
      final t = ppgTimes[i];
      if (t >= ts + lo && t <= ts + hi) {
        used.add(i);
        ptt.add((t - ts) * 1000.0);
        break; // earliest foot in the window
      }
    }
  }
  return ptt;
}

@immutable
class PttSummary {
  const PttSummary({
    required this.n,
    required this.median,
    required this.sd,
    required this.iqr,
    required this.pairYield,
  });

  final int n;
  final double median;
  final double sd;
  final double iqr;
  final double pairYield;
}

/// Drop intervals beyond Tukey's fence before anything is concluded from the set.
///
/// **The gate was deciding on untrimmed pairs, and that is what refused a usable capture.** A
/// standard deviation is not robust: pairing a systolic chest event to a diastolic finger foot
/// produces an interval a hundred milliseconds from its neighbours, and two or three of those in
/// sixty inflate the spread far past anything the recording actually did. The observed failure was
/// 70.6 ms across 61 pairs, which is not what 61 coherent intervals look like.
///
/// The backend has always done this — `trimmed_session_ptt` applies the same 1.5x IQR fence before
/// computing the session value — so the handset was refusing sessions on a statistic the server
/// would never have used. Same fence, same multiplier, now on both sides.
///
/// Guards match the backend's: fewer than four values has no defined quartile and is returned
/// whole, and a degenerate fence that would retain nothing falls back to the full set.
List<double> tukeyTrim(List<double> values) {
  if (values.length < 4) return values;
  final q1 = percentile(values, 25);
  final q3 = percentile(values, 75);
  final fence = iqrFenceMultiplier * (q3 - q1);
  final retained = [
    for (final v in values)
      if (v >= q1 - fence && v <= q3 + fence) v,
  ];
  return retained.isEmpty ? values : retained;
}

PttSummary summarise(List<double> pttMs, int nScgBeats) {
  if (pttMs.isEmpty) {
    return const PttSummary(
      n: 0,
      median: double.nan,
      sd: double.nan,
      iqr: double.nan,
      pairYield: 0.0,
    );
  }
  return PttSummary(
    n: pttMs.length,
    median: median(pttMs),
    // ddof=1 in the reference: a sample standard deviation, not a population one.
    sd: pttMs.length > 1 ? std(pttMs, ddof: 1) : double.nan,
    iqr: percentile(pttMs, 75) - percentile(pttMs, 25),
    pairYield: pttMs.length / math.max(nScgBeats, 1),
  );
}

/// Why the gate closed. Each maps onto a backend `rejection_reason`.
enum GateFailure {
  insufficientBeats,
  chestBeatDetectionUnreliable,
  fingerBeatDetectionUnreliable,
  sensorsDisagree,
  lowPairYield,
  pttTooVariable,
}

@immutable
class GateResult {
  const GateResult({required this.passed, this.failure, this.detail});

  final bool passed;
  final GateFailure? failure;

  /// Human-readable, for logs and the developer build. Never shown as a clinical statement.
  final String? detail;

  static const ok = GateResult(passed: true);
}

/// Four independent checks, cheapest first. Refuse rather than guess.
GateResult qualityGate({
  required double scgHr,
  required double scgSpectralHr,
  required double ppgHr,
  required double ppgSpectralHr,
  required PttSummary summary,
}) {
  if (summary.n < minPairs) {
    return GateResult(
      passed: false,
      failure: GateFailure.insufficientBeats,
      detail: 'only ${summary.n} paired beats, need $minPairs',
    );
  }

  for (final check in [
    ('chest', scgHr, scgSpectralHr, GateFailure.chestBeatDetectionUnreliable),
    ('finger', ppgHr, ppgSpectralHr, GateFailure.fingerBeatDetectionUnreliable),
  ]) {
    final (name, a, b, failure) = check;
    if (!a.isFinite || !b.isFinite) {
      return GateResult(
        passed: false,
        failure: failure,
        detail: '$name heart rate could not be estimated',
      );
    }
    // Before the agreement check, because two estimators agreeing on an impossible rate is a
    // detector describing itself, not a measurement. See [hrPlausibleMinBpm].
    if (a < hrPlausibleMinBpm || a > hrPlausibleMaxBpm) {
      return GateResult(
        passed: false,
        failure: failure,
        detail:
            '$name rate ${a.toStringAsFixed(1)} bpm is outside the seated plausible window '
            '${hrPlausibleMinBpm.toStringAsFixed(0)}-'
            '${hrPlausibleMaxBpm.toStringAsFixed(0)} bpm',
      );
    }
    // EC13 at this sensor's own peak-detected rate, as the reference does.
    final tol = hrToleranceBpm(a);
    if ((a - b).abs() > tol) {
      return GateResult(
        passed: false,
        failure: failure,
        detail:
            '$name beat detection unreliable: '
            'peak ${a.toStringAsFixed(1)} bpm vs spectral ${b.toStringAsFixed(1)} bpm '
            '= ${(a - b).abs().toStringAsFixed(1)} bpm apart, EC13 limit '
            '${tol.toStringAsFixed(1)} bpm at ${a.toStringAsFixed(0)} bpm',
      );
    }
  }

  // The strongest check, and the one a single-sensor product has no way to run: if the chest and
  // the finger disagree about the heart rate, they are not seeing the same heartbeats, so no
  // transit time exists between them.
  // At the *lower* of the two rates — the conservative reading, and the reference's — but with
  // the consumer-hardware floor rather than EC13's. See [crossSensorFloorBpm] for what that costs.
  final crossTol = crossSensorToleranceBpm(math.min(scgHr, ppgHr));
  if ((scgHr - ppgHr).abs() > crossTol) {
    return GateResult(
      passed: false,
      failure: GateFailure.sensorsDisagree,
      detail:
          'chest ${scgHr.toStringAsFixed(1)} bpm vs finger ${ppgHr.toStringAsFixed(1)} bpm '
          '= ${(scgHr - ppgHr).abs().toStringAsFixed(1)} bpm apart, cross-sensor limit '
          '${crossTol.toStringAsFixed(1)} bpm — not the same heartbeats',
    );
  }

  if (summary.pairYield < minPairYield) {
    return GateResult(
      passed: false,
      failure: GateFailure.lowPairYield,
      detail:
          'only ${(100 * summary.pairYield).toStringAsFixed(1)}% of beats paired, '
          'need ${(100 * minPairYield).toStringAsFixed(0)}%',
    );
  }

  if (summary.sd.isFinite && summary.sd > maxPttSdMs) {
    return GateResult(
      passed: false,
      failure: GateFailure.pttTooVariable,
      detail:
          'PTT spread ${summary.sd.toStringAsFixed(1)} ms, '
          'ceiling ${maxPttSdMs.toStringAsFixed(1)} ms',
    );
  }

  return GateResult.ok;
}

@immutable
class PttAnalysis {
  const PttAnalysis({
    required this.gate,
    required this.pttMs,
    required this.summary,
    required this.nScgBeats,
    required this.nPpgFeet,
    required this.scgHr,
    required this.ppgHr,
    required this.scgSpectralHr,
    required this.ppgSpectralHr,
    this.scgHarmonicSuppressed = false,
    this.ppgHarmonicSuppressed = false,
    this.nPairedBeforeTrim = 0,
    this.sdBeforeTrimMs = double.nan,
  });

  final GateResult gate;

  /// One interval per paired beat, milliseconds. Present whether or not the gate passed, so a
  /// caller can report the count; the *caller* decides whether they may be submitted.
  final List<double> pttMs;

  final PttSummary summary;
  final int nScgBeats;
  final int nPpgFeet;
  final double scgHr;
  final double ppgHr;
  final double scgSpectralHr;
  final double ppgSpectralHr;

  /// Whether either detector needed its second pass. Logged by the pipeline; never submitted.
  final bool scgHarmonicSuppressed;
  final bool ppgHarmonicSuppressed;

  /// Pairs found before Tukey trimming, and the spread they had. Diagnostics only.
  final int nPairedBeforeTrim;
  final double sdBeforeTrimMs;
}

/// One capture in, one analysis out. The whole chain.
PttAnalysis analyseCapture({
  required List<double> scg,
  required double fsScg,
  required List<double> ppg,
  required double fsPpg,
  // Parameters, exactly as `pair_beats(scg_t, ppg_t, lo=PTT_MIN_S, hi=PTT_MAX_S)` takes them in
  // the reference. Production uses the defaults; `ptt_reference_test.dart` passes the reference's
  // own 0.08-0.40 so the port can still be proved identical to the Python at identical constants.
  //
  // That separation is the point: whether the algorithm matches and how the product is tuned are
  // different questions, and collapsing them meant a deliberate tuning change read as a port
  // defect.
  double pttLoSeconds = pttMinSeconds,
  double pttHiSeconds = pttMaxSeconds,
  // Off for the fidelity test, which compares against a Python run that does not trim. Production
  // trims: see [tukeyTrim] for why the untrimmed spread was refusing usable captures.
  bool trimOutliers = true,
}) {
  final scgBeats = detectScgBeats(scg, fsScg);
  final ppgFeet = detectPpgFeet(ppg, fsPpg);
  final paired = pairBeats(
    scgBeats.times,
    ppgFeet.times,
    lo: pttLoSeconds,
    hi: pttHiSeconds,
  );
  final pttMs = trimOutliers ? tukeyTrim(paired) : paired;
  final summary = summarise(pttMs, scgBeats.times.length);

  // Kept so the log can show what trimming did. A capture whose spread only comes inside the
  // ceiling after a third of its pairs were dropped is a different thing from one that was always
  // coherent, and the difference should be visible rather than absorbed.
  final untrimmed = summarise(paired, scgBeats.times.length);

  return PttAnalysis(
    gate: qualityGate(
      scgHr: scgBeats.peakHr,
      scgSpectralHr: scgBeats.spectralHr,
      ppgHr: ppgFeet.peakHr,
      ppgSpectralHr: ppgFeet.spectralHr,
      summary: summary,
    ),
    pttMs: pttMs,
    summary: summary,
    nScgBeats: scgBeats.times.length,
    nPpgFeet: ppgFeet.times.length,
    scgHr: scgBeats.peakHr,
    ppgHr: ppgFeet.peakHr,
    scgSpectralHr: scgBeats.spectralHr,
    ppgSpectralHr: ppgFeet.spectralHr,
    scgHarmonicSuppressed: scgBeats.harmonicSuppressed,
    ppgHarmonicSuppressed: ppgFeet.harmonicSuppressed,
    nPairedBeforeTrim: paired.length,
    sdBeforeTrimMs: untrimmed.sd,
  );
}
