/// The Tera signal chain, ported from the ML team's `tera_ptt.py`.
///
///     SCG (accelerometer, chest)  -+
///                                  +-> beat pairing -> per-beat PTT -> quality gate
///     PPG (camera + torch, finger)-+
///
/// # Why this is Dart and not a server call
///
/// The ML team's reference runs in Python on a backend and takes raw sample arrays. Invariant 2
/// says raw waveform never leaves the handset, and that is a regulatory claim in the pitch, not a
/// preference. So the chain runs here, the raw arrays stay on the phone, and only per-beat
/// intervals and quality figures are submitted.
///
/// # Fidelity
///
/// Ported from the reference's **scipy-free fallback path**, which it ships for exactly this
/// case: an FFT brick-wall band-pass, an FFT Hilbert transform, and a simple peak finder. That
/// path is reproducible in Dart exactly; a Butterworth `sosfiltfilt` chain would not have been.
/// `test/ptt_reference_test.dart` checks this implementation against vectors generated by the
/// Python with scipy disabled.
///
/// PTT **shortens** as blood pressure **rises** (Moens-Korteweg). A sign error here is silent and
/// catastrophic, so the direction is asserted in the tests, as it is in the reference.
library;

import 'dart:math' as math;

import 'package:meta/meta.dart';

import 'signal_ops.dart';

// ------------------------------------------------------------------- tunables
//
// Reproduced from `tera_ptt.py`. These are the ML team's validated figures and are not to be
// retuned here: `MAX_PTT_SD_MS` in particular is the proposal's 10 ms sensing-chain budget, and
// on the PhysioNet PTT dataset it keeps 6 of 8 seated recordings and rejects 13 of 16 walking or
// running ones. Changing a number in this block silently changes what the product accepts.

/// Physiological acceptance window for a single transit time, seconds.
const double pttMinSeconds = 0.08;
const double pttMaxSeconds = 0.40;

/// Dual-estimator tolerance: peak-detected HR against spectral HR, on one sensor.
const double hrTolBpm = 10.0;

/// Cross-sensor tolerance: chest HR against finger HR. The check a single-sensor product cannot
/// run, and a direct test of the simultaneity the whole method assumes.
const double crossHrTolBpm = 8.0;

/// Paired beats needed before a median means anything.
const int minPairs = 12;

/// Fraction of detected SCG beats that must find a partner.
const double minPairYield = 0.50;

/// Within-session dispersion ceiling, milliseconds.
const double maxPttSdMs = 10.0;

/// Envelope fraction marking aortic valve opening. Swept, not guessed: 0.20 overshoots to -25 ms
/// and the envelope peak itself is +18 ms.
const double scgOnsetFrac = 0.82;

/// Beats faster than this are not beats.
const int maxBpm = 200;

@immutable
class BeatDetection {
  const BeatDetection({
    required this.times,
    required this.peakHr,
    required this.spectralHr,
  });

  /// Event times in seconds from the start of the capture.
  final List<double> times;

  /// Heart rate from the median interval between detected events.
  final double peakHr;

  /// Independent heart rate from the dominant envelope frequency.
  final double spectralHr;

  static const empty = BeatDetection(
    times: [],
    peakHr: double.nan,
    spectralHr: double.nan,
  );
}

/// Aortic-opening times from chest SCG.
///
/// The envelope *peak* sits inside the ejection complex and the smoothing kernel pushes it later
/// still, so each peak is backtracked to [scgOnsetFrac] of its rise, with linear interpolation
/// between the straddling samples — at 200 Hz one sample is 5 ms, a large slice of a 10-50 ms
/// signal.
BeatDetection detectScgBeats(List<double> scg, double fs) {
  final env = envelope(scg, fs, 1.0, 25.0);
  if (env.length < fs * 3) return BeatDetection.empty;

  final peaks = findPeaks(
    env,
    distance: (fs * 60 / maxBpm).toInt(),
    prominence: 0.5 * std(env),
  );

  final onsets = <double>[];
  final back = (0.12 * fs).toInt();
  for (final p in peaks) {
    final a = math.max(0, p - back);
    final seg = env.sublist(a, p + 1);
    if (seg.length < 2) {
      onsets.add(p.toDouble());
      continue;
    }
    final base = seg.reduce(math.min);
    final thr = base + scgOnsetFrac * (env[p] - base);
    int? firstAbove;
    for (int i = 0; i < seg.length; i++) {
      if (seg[i] >= thr) {
        firstAbove = i;
        break;
      }
    }
    if (firstAbove == null) {
      onsets.add(p.toDouble());
      continue;
    }
    double i = firstAbove.toDouble();
    if (firstAbove > 0 && seg[firstAbove] > seg[firstAbove - 1]) {
      i = (firstAbove - 1) +
          (thr - seg[firstAbove - 1]) / (seg[firstAbove] - seg[firstAbove - 1]);
    }
    onsets.add(a + i);
  }

  final times = uniqueRounded(onsets.map((o) => o / fs).toList(), 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectralHr(env, fs),
  );
}

/// A real PPG has a fast systolic upstroke and a slow decay, so its *derivative* is positively
/// skewed. Phone cameras often deliver it inverted, because more blood absorbs more light.
///
/// Testing the skew of the amplitude is the wrong test and gives the wrong answer. Testing the
/// skew of the derivative is the right one. The reference notes this cost a debugging session;
/// do not "simplify" it back.
List<double> orientPpg(List<double> x) {
  final d = gradient(x);
  final dm = mean(d);
  final ds = std(d);
  double acc = 0;
  for (final v in d) {
    acc += math.pow(v - dm, 3).toDouble();
  }
  final skew = (acc / d.length) / (math.pow(ds, 3) + 1e-12);
  return skew < 0 ? x.map((v) => -v).toList() : List<double>.from(x);
}

/// Pulse-foot times at the fingertip.
///
/// **Intersecting tangents, not argmin.** At 30 fps one sample is 33 ms and the foot is a flat
/// minimum, so argmin lands a sample or two early — measured at -39 ms. Intersecting the
/// diastolic baseline with the tangent at maximum upstroke is sub-sample accurate, and is the
/// standard fiducial in the PTT literature.
BeatDetection detectPpgFeet(List<double> ppg, double fs) {
  final x = orientPpg(ppg);
  final f = bandpass(x, fs, 0.5, math.min(8.0, 0.45 * fs));
  if (f.length < fs * 3) return BeatDetection.empty;

  final peaks = findPeaks(
    f,
    distance: (fs * 60 / maxBpm).toInt(),
    prominence: 0.3 * std(f),
  );
  if (peaks.length < 3) return BeatDetection.empty;

  final gaps = <double>[
    for (int i = 1; i < peaks.length; i++) (peaks[i] - peaks[i - 1]).toDouble(),
  ];
  final ibi = median(gaps);
  final win = math.min(0.25 * ibi, 0.20 * fs).toInt();

  final d = gradient(f);
  final feet = <double>[];
  for (final p in peaks) {
    final a = math.max(0, p - win);
    if (p - a < 3) continue;
    final seg = f.sublist(a, p + 1);
    final dseg = d.sublist(a, p + 1);

    int iMin = 0;
    for (int i = 1; i < seg.length; i++) {
      if (seg[i] < seg[iMin]) iMin = i;
    }
    if (p - (a + iMin) < 2) continue;

    int iSlope = iMin;
    for (int i = iMin; i < dseg.length; i++) {
      if (dseg[i] > dseg[iSlope]) iSlope = i;
    }
    final slope = dseg[iSlope];
    if (slope <= 1e-12) {
      feet.add((a + iMin) / fs);
      continue;
    }
    // baseline y = seg[iMin]; tangent y = seg[iSlope] + slope * (i - iSlope)
    double iFoot = iSlope + (seg[iMin] - seg[iSlope]) / slope;
    iFoot = iFoot.clamp(0, (p - a).toDouble());
    feet.add((a + iFoot) / fs);
  }

  final times = uniqueRounded(feet, 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectralHr(hilbertEnvelope(f), fs),
  );
}

double _hrFromTimes(List<double> times) {
  final rr = <double>[
    for (int i = 1; i < times.length; i++)
      if (times[i] - times[i - 1] > 60.0 / maxBpm && times[i] - times[i - 1] < 60.0 / 40.0)
        times[i] - times[i - 1],
  ];
  if (rr.isEmpty) return double.nan;
  return 60.0 / median(rr);
}

/// Match each SCG beat to the first unclaimed PPG foot inside the PTT window.
///
/// PTT is defined between two events of **the same cardiac cycle**. Pairing a beat with a foot
/// from a different cycle does not degrade the number, it invents one. So an unmatched beat is
/// dropped, never stretched to fit.
List<double> pairBeats(List<double> scgTimes, List<double> ppgTimes) {
  if (scgTimes.isEmpty || ppgTimes.isEmpty) return const [];
  final used = <int>{};
  final ptt = <double>[];
  for (final ts in scgTimes) {
    for (int i = 0; i < ppgTimes.length; i++) {
      if (used.contains(i)) continue;
      final t = ppgTimes[i];
      if (t >= ts + pttMinSeconds && t <= ts + pttMaxSeconds) {
        used.add(i);
        ptt.add((t - ts) * 1000.0);
        break; // earliest foot in the window
      }
    }
  }
  return ptt;
}

@immutable
class PttSummary {
  const PttSummary({
    required this.n,
    required this.median,
    required this.sd,
    required this.iqr,
    required this.pairYield,
  });

  final int n;
  final double median;
  final double sd;
  final double iqr;
  final double pairYield;
}

PttSummary summarise(List<double> pttMs, int nScgBeats) {
  if (pttMs.isEmpty) {
    return const PttSummary(
      n: 0,
      median: double.nan,
      sd: double.nan,
      iqr: double.nan,
      pairYield: 0.0,
    );
  }
  return PttSummary(
    n: pttMs.length,
    median: median(pttMs),
    // ddof=1 in the reference: a sample standard deviation, not a population one.
    sd: pttMs.length > 1 ? std(pttMs, ddof: 1) : double.nan,
    iqr: percentile(pttMs, 75) - percentile(pttMs, 25),
    pairYield: pttMs.length / math.max(nScgBeats, 1),
  );
}

/// Why the gate closed. Each maps onto a backend `rejection_reason`.
enum GateFailure {
  insufficientBeats,
  chestBeatDetectionUnreliable,
  fingerBeatDetectionUnreliable,
  sensorsDisagree,
  lowPairYield,
  pttTooVariable,
}

@immutable
class GateResult {
  const GateResult({required this.passed, this.failure, this.detail});

  final bool passed;
  final GateFailure? failure;

  /// Human-readable, for logs and the developer build. Never shown as a clinical statement.
  final String? detail;

  static const ok = GateResult(passed: true);
}

/// Four independent checks, cheapest first. Refuse rather than guess.
GateResult qualityGate({
  required double scgHr,
  required double scgSpectralHr,
  required double ppgHr,
  required double ppgSpectralHr,
  required PttSummary summary,
}) {
  if (summary.n < minPairs) {
    return GateResult(
      passed: false,
      failure: GateFailure.insufficientBeats,
      detail: 'only ${summary.n} paired beats, need $minPairs',
    );
  }

  for (final check in [
    (
      'chest',
      scgHr,
      scgSpectralHr,
      GateFailure.chestBeatDetectionUnreliable,
    ),
    (
      'finger',
      ppgHr,
      ppgSpectralHr,
      GateFailure.fingerBeatDetectionUnreliable,
    ),
  ]) {
    final (name, a, b, failure) = check;
    if (!a.isFinite || !b.isFinite) {
      return GateResult(
        passed: false,
        failure: failure,
        detail: '$name heart rate could not be estimated',
      );
    }
    if ((a - b).abs() > hrTolBpm) {
      return GateResult(
        passed: false,
        failure: failure,
        detail: '$name beat detection unreliable '
            '(${(a - b).abs().toStringAsFixed(0)} bpm disagreement)',
      );
    }
  }

  // The strongest check, and the one a single-sensor product has no way to run: if the chest and
  // the finger disagree about the heart rate, they are not seeing the same heartbeats, so no
  // transit time exists between them.
  if ((scgHr - ppgHr).abs() > crossHrTolBpm) {
    return GateResult(
      passed: false,
      failure: GateFailure.sensorsDisagree,
      detail: 'chest and finger disagree by '
          '${(scgHr - ppgHr).abs().toStringAsFixed(0)} bpm, not the same heartbeats',
    );
  }

  if (summary.pairYield < minPairYield) {
    return GateResult(
      passed: false,
      failure: GateFailure.lowPairYield,
      detail: 'only ${(100 * summary.pairYield).toStringAsFixed(0)}% of beats paired',
    );
  }

  if (summary.sd.isFinite && summary.sd > maxPttSdMs) {
    return GateResult(
      passed: false,
      failure: GateFailure.pttTooVariable,
      detail: 'PTT too variable (${summary.sd.toStringAsFixed(0)} ms spread)',
    );
  }

  return GateResult.ok;
}

@immutable
class PttAnalysis {
  const PttAnalysis({
    required this.gate,
    required this.pttMs,
    required this.summary,
    required this.nScgBeats,
    required this.nPpgFeet,
    required this.scgHr,
    required this.ppgHr,
    required this.scgSpectralHr,
    required this.ppgSpectralHr,
  });

  final GateResult gate;

  /// One interval per paired beat, milliseconds. Present whether or not the gate passed, so a
  /// caller can report the count; the *caller* decides whether they may be submitted.
  final List<double> pttMs;

  final PttSummary summary;
  final int nScgBeats;
  final int nPpgFeet;
  final double scgHr;
  final double ppgHr;
  final double scgSpectralHr;
  final double ppgSpectralHr;
}

/// One capture in, one analysis out. The whole chain.
PttAnalysis analyseCapture({
  required List<double> scg,
  required double fsScg,
  required List<double> ppg,
  required double fsPpg,
}) {
  final scgBeats = detectScgBeats(scg, fsScg);
  final ppgFeet = detectPpgFeet(ppg, fsPpg);
  final pttMs = pairBeats(scgBeats.times, ppgFeet.times);
  final summary = summarise(pttMs, scgBeats.times.length);

  return PttAnalysis(
    gate: qualityGate(
      scgHr: scgBeats.peakHr,
      scgSpectralHr: scgBeats.spectralHr,
      ppgHr: ppgFeet.peakHr,
      ppgSpectralHr: ppgFeet.spectralHr,
      summary: summary,
    ),
    pttMs: pttMs,
    summary: summary,
    nScgBeats: scgBeats.times.length,
    nPpgFeet: ppgFeet.times.length,
    scgHr: scgBeats.peakHr,
    ppgHr: ppgFeet.peakHr,
    scgSpectralHr: scgBeats.spectralHr,
    ppgSpectralHr: ppgFeet.spectralHr,
  );
}
