/// The Tera signal chain, ported from the ML team's `tera_ptt.py`.
///
///     SCG (accelerometer, chest)  -+
///                                  +-> beat pairing -> per-beat PTT -> quality gate
///     PPG (camera + torch, finger)-+
///
/// # Why this is Dart and not a server call
///
/// The ML team's reference runs in Python on a backend and takes raw sample arrays. Invariant 2
/// says raw waveform never leaves the handset, and that is a regulatory claim in the pitch, not a
/// preference. So the chain runs here, the raw arrays stay on the phone, and only per-beat
/// intervals and quality figures are submitted.
///
/// # Fidelity
///
/// Ported from the reference's **scipy-free fallback path**, which it ships for exactly this
/// case: an FFT brick-wall band-pass, an FFT Hilbert transform, and a simple peak finder. That
/// path is reproducible in Dart exactly; a Butterworth `sosfiltfilt` chain would not have been.
/// `test/ptt_reference_test.dart` checks this implementation against vectors generated by the
/// Python with scipy disabled.
///
/// PTT **shortens** as blood pressure **rises** (Moens-Korteweg). A sign error here is silent and
/// catastrophic, so the direction is asserted in the tests, as it is in the reference.
library;

import 'dart:math' as math;

import 'package:meta/meta.dart';

import 'signal_ops.dart';

// ------------------------------------------------------------------- tunables
//
// Reproduced from `tera_ptt.py`. These are the ML team's validated figures and are not to be
// retuned here: `MAX_PTT_SD_MS` in particular is the proposal's 10 ms sensing-chain budget, and
// on the PhysioNet PTT dataset it keeps 6 of 8 seated recordings and rejects 13 of 16 walking or
// running ones. Changing a number in this block silently changes what the product accepts.

/// Physiological acceptance window for a single transit time, seconds.
const double pttMinSeconds = 0.08;
const double pttMaxSeconds = 0.40;

/// ANSI/AAMI EC13 readout tolerance: ten percent of the rate, or five bpm, whichever is greater.
///
/// **This replaces two flat constants — 10 bpm dual-estimator and 8 bpm cross-sensor — and the
/// difference is not cosmetic.** EC13 scales with heart rate because a counting error scales with
/// heart rate: at 60 bpm a 10 bpm disagreement is a sixth of the signal, at 130 bpm it is well
/// inside one beat's worth of edge placement. A flat number is therefore wrong in both directions
/// at once, and the port had one:
///
/// | HR | EC13 | old flat dual | old flat cross |
/// |----|------|---------------|----------------|
/// | 60 | 6 | 10 (too lax) | 8 (too lax) |
/// | 80 | 8 | 10 | 8 |
/// | 100 | 10 | 10 | 8 (too strict) |
/// | 130 | 13 | 10 (too strict) | 8 (too strict) |
///
/// The cross-sensor constant was the worse of the two: stricter than the reference at every rate
/// above 80 bpm. An elevated heart rate is the state of a nervous person taking their first
/// reading, and of much of the population this product exists for — so the gate was tightest
/// exactly where it should have been loosest, and refused captures the ML reference accepts.
///
/// Applying a single-device readout spec to the agreement between two of our own estimates is the
/// conservative reading, and the reference says so: if each estimator is independently allowed E,
/// their difference could reach 2E, and this demands E.
const double ec13Relative = 0.10;
const double ec13FloorBpm = 5.0;

double hrToleranceBpm(double hrBpm) {
  if (!hrBpm.isFinite || hrBpm <= 0) return ec13FloorBpm;
  return math.max(ec13Relative * hrBpm, ec13FloorBpm);
}

/// Paired beats needed before a median means anything.
const int minPairs = 12;

/// Fraction of detected SCG beats that must find a partner.
const double minPairYield = 0.50;

/// Within-session dispersion ceiling, milliseconds.
const double maxPttSdMs = 10.0;

/// Envelope fraction marking aortic valve opening. Swept, not guessed: 0.20 overshoots to -25 ms
/// and the envelope peak itself is +18 ms.
const double scgOnsetFrac = 0.82;

/// Beats faster than this are not beats.
const int maxBpm = 200;

/// Physiologically plausible seated heart rate, bpm. The reference's `HR_PLAUSIBLE["seated"]`.
///
/// **Present in `tera_ptt.py` and missing from this port until a real capture needed it.** The
/// reference applies it in `hr_gate`, which decides whether a *rate* may be reported; it is applied
/// here, in the PTT gate, as well.
///
/// The case that forced it: the dual-estimator check compares peak detection against spectral
/// estimation on the assumption that two independent methods do not fail the same way. Usually
/// true. But a chest whose diastolic complex nearly matches its systolic one puts so much energy at
/// the harmonic that *both* estimators lock onto it — and then they agree, within EC13, on a rate
/// that is wrong by a factor of two or three. The check passes and the capture is accepted with a
/// heart rate of 187 bpm for a patient sitting still at 58.
///
/// Agreement between two fooled estimators is not evidence. A window is, because it is a fact about
/// people rather than about either method: nobody produces 187 bpm sitting quietly in a chair, and
/// a capture claiming they did is describing its own detector. Invariant 7 — where the signal is
/// ambiguous, refuse rather than report.
///
/// `maxBpm` does not cover this. It is 200, the fastest a heart can go at all, and is the
/// refractory period's input; this is the range a *seated resting* capture may occupy.
const double hrPlausibleMinBpm = 45.0;
const double hrPlausibleMaxBpm = 140.0;

// --------------------------------------------------------- harmonic suppression
//
// **The first real captures failed here, on every axis, and the numbers name the cause:**
//
//     peak 119.2 bpm vs spectral 58.0 bpm = 61.2 bpm apart
//
// 119.2 / 58.0 = 2.06. The time-domain detector was counting the chest wall twice per cardiac
// cycle — aortic *opening* and aortic *closing*, the "lub" and the "dub" — while the spectral
// estimator correctly locked onto the fundamental. Both events produce a genuine bump in the
// Hilbert envelope with a real trough between them, so no amount of prominence tuning separates
// them: they are both real, and only one of them is the beat.
//
// **The refractory period the reference already has cannot fix this, and it is worth being precise
// about why.** `find_peaks(distance=int(fs * 60 / max_bpm))` with `max_bpm = 200` is a 300 ms
// floor, and it is already in force — at the 468 Hz this handset achieved, that is 140 samples.
// But the spurious peaks sat 503 ms apart (119.2 bpm), comfortably *outside* 300 ms. A refractory
// derived from the fastest heart a human can have says nothing useful about a heart beating at 58.
// The systolic ejection period at rest is 300-400 ms, so the aortic-closing bump lands just past
// a floor built for 200 bpm. The floor is not too small by a little; it is answering a different
// question.
//
// So the second pass derives its refractory from the fundamental the spectral estimator found,
// which is the only estimate available that is immune to this failure — a harmonic adds energy at
// 2f, it does not move the peak at f.

/// Fraction of the spectral fundamental period used as the refractory period on the second pass.
///
/// Three quarters of a beat: wide enough to swallow a diastolic bump at any physiological systolic
/// ejection period, narrow enough that genuine beat-to-beat variation — which at rest is a few
/// percent of the interval, not a quarter of it — still resolves.
const double harmonicRefractoryFraction = 0.75;

/// How far above the spectral fundamental the peak rate must sit before a second pass is tried.
///
/// Halfway to a doubling. A detector genuinely running 50% fast against the fundamental is not
/// making a small counting error, and the honest readings this must not disturb sit within EC13 of
/// the fundamental — a few percent, nowhere near this.
const double harmonicSuspicionRatio = 1.5;

@immutable
class BeatDetection {
  const BeatDetection({
    required this.times,
    required this.peakHr,
    required this.spectralHr,
    this.harmonicSuppressed = false,
  });

  /// Event times in seconds from the start of the capture.
  final List<double> times;

  /// Heart rate from the median interval between detected events.
  final double peakHr;

  /// Independent heart rate from the dominant envelope frequency.
  final double spectralHr;

  /// True when the second pass ran and its result was adopted.
  ///
  /// Reported rather than silent: a capture that needed harmonic suppression is a capture whose
  /// diastolic complex is as strong as its systolic one, which is a fact about how the phone sat
  /// on the sternum and is worth seeing in a log before it is worth hiding in a median.
  final bool harmonicSuppressed;

  static const empty = BeatDetection(
    times: [],
    peakHr: double.nan,
    spectralHr: double.nan,
  );
}

/// Heart rate implied by a run of peak *indices*, in bpm.
///
/// Same plausibility window as [_hrFromTimes], applied to sample gaps rather than to the
/// backtracked event times. Used only to decide whether a second pass helped: the two differ by
/// the backtrack, which shifts every peak by roughly the same amount and so leaves the intervals —
/// and therefore the rate — alone.
double _hrFromPeakIndices(List<int> peaks, double fs) {
  final rr = <double>[
    for (int i = 1; i < peaks.length; i++)
      if ((peaks[i] - peaks[i - 1]) / fs > 60.0 / maxBpm &&
          (peaks[i] - peaks[i - 1]) / fs < 60.0 / 40.0)
        (peaks[i] - peaks[i - 1]) / fs,
  ];
  if (rr.isEmpty) return double.nan;
  return 60.0 / median(rr);
}

/// Peak detection, with a second pass when the first looks like it counted harmonics.
///
/// Pass one is the reference's, unchanged, and is what almost every capture will use. Pass two
/// only runs when the rate it produced is at least [harmonicSuspicionRatio] times the spectral
/// fundamental, and **its result is adopted only if it agrees with that fundamental better than
/// pass one did.** A wider refractory that makes the disagreement worse is not a correction, and
/// is discarded.
///
/// # What this costs, stated plainly
///
/// The dual-estimator check compares the peak rate against the spectral rate, and its value is
/// that the two are arrived at independently. On a capture where pass two fires, they no longer
/// are: the spectral estimate has constrained the peak search. That limb of the gate is weaker for
/// those captures and it would be dishonest to pretend otherwise.
///
/// Two things keep it from being decorative. The constraint only ever *removes* peaks, so it
/// cannot manufacture a beat train from a recording that has none — a signal with no rhythm still
/// fails, because a wider refractory on noise does not produce a regular series. And the
/// cross-sensor check is untouched: chest rate against finger rate, two different sensors reading
/// two different physical quantities, which `quality_gate` already calls the strongest check it
/// has. That limb remains fully independent, and a capture that passes the gate still had to
/// satisfy it.
({List<int> peaks, bool suppressed}) _detectPeaks({
  required List<double> trace,
  required double fs,
  required double prominence,
  required double spectralHrBpm,
}) {
  final baseDistance = (fs * 60 / maxBpm).toInt();
  final first = findPeaks(
    trace,
    distance: baseDistance,
    prominence: prominence,
  );

  if (!spectralHrBpm.isFinite || spectralHrBpm <= 0) {
    return (peaks: first, suppressed: false);
  }
  final firstHr = _hrFromPeakIndices(first, fs);
  if (!firstHr.isFinite || firstHr < spectralHrBpm * harmonicSuspicionRatio) {
    return (peaks: first, suppressed: false);
  }

  // Never narrower than the reference's floor: this pass exists to widen.
  final widened = math.max(
    baseDistance,
    (harmonicRefractoryFraction * fs * 60.0 / spectralHrBpm).round(),
  );
  final second = findPeaks(trace, distance: widened, prominence: prominence);
  final secondHr = _hrFromPeakIndices(second, fs);
  if (!secondHr.isFinite) return (peaks: first, suppressed: false);

  if ((secondHr - spectralHrBpm).abs() >= (firstHr - spectralHrBpm).abs()) {
    return (peaks: first, suppressed: false);
  }
  return (peaks: second, suppressed: true);
}

/// Aortic-opening times from chest SCG.
///
/// The envelope *peak* sits inside the ejection complex and the smoothing kernel pushes it later
/// still, so each peak is backtracked to [scgOnsetFrac] of its rise, with linear interpolation
/// between the straddling samples — at 200 Hz one sample is 5 ms, a large slice of a 10-50 ms
/// signal.
BeatDetection detectScgBeats(List<double> scg, double fs) {
  final env = envelope(scg, fs, 1.0, 25.0);
  if (env.length < fs * 3) return BeatDetection.empty;

  // The spectral estimate is computed first here, because the second pass needs it. It reads the
  // envelope's dominant frequency and is unaffected by the double-counting: a harmonic puts energy
  // at 2f, it does not move the peak at f.
  final spectral = spectralHr(env, fs);
  final detected = _detectPeaks(
    trace: env,
    fs: fs,
    prominence: 0.5 * std(env),
    spectralHrBpm: spectral,
  );
  final peaks = detected.peaks;

  final onsets = <double>[];
  final back = (0.12 * fs).toInt();
  for (final p in peaks) {
    final a = math.max(0, p - back);
    final seg = env.sublist(a, p + 1);
    if (seg.length < 2) {
      onsets.add(p.toDouble());
      continue;
    }
    final base = seg.reduce(math.min);
    final thr = base + scgOnsetFrac * (env[p] - base);
    int? firstAbove;
    for (int i = 0; i < seg.length; i++) {
      if (seg[i] >= thr) {
        firstAbove = i;
        break;
      }
    }
    if (firstAbove == null) {
      onsets.add(p.toDouble());
      continue;
    }
    double i = firstAbove.toDouble();
    if (firstAbove > 0 && seg[firstAbove] > seg[firstAbove - 1]) {
      i =
          (firstAbove - 1) +
          (thr - seg[firstAbove - 1]) / (seg[firstAbove] - seg[firstAbove - 1]);
    }
    onsets.add(a + i);
  }

  final times = uniqueRounded(onsets.map((o) => o / fs).toList(), 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectral,
    harmonicSuppressed: detected.suppressed,
  );
}

/// A real PPG has a fast systolic upstroke and a slow decay, so its *derivative* is positively
/// skewed. Phone cameras often deliver it inverted, because more blood absorbs more light.
///
/// Testing the skew of the amplitude is the wrong test and gives the wrong answer. Testing the
/// skew of the derivative is the right one. The reference notes this cost a debugging session;
/// do not "simplify" it back.
List<double> orientPpg(List<double> x) {
  final d = gradient(x);
  final dm = mean(d);
  final ds = std(d);
  double acc = 0;
  for (final v in d) {
    acc += math.pow(v - dm, 3).toDouble();
  }
  final skew = (acc / d.length) / (math.pow(ds, 3) + 1e-12);
  return skew < 0 ? x.map((v) => -v).toList() : List<double>.from(x);
}

/// Pulse-foot times at the fingertip.
///
/// **Intersecting tangents, not argmin.** At 30 fps one sample is 33 ms and the foot is a flat
/// minimum, so argmin lands a sample or two early — measured at -39 ms. Intersecting the
/// diastolic baseline with the tangent at maximum upstroke is sub-sample accurate, and is the
/// standard fiducial in the PTT literature.
BeatDetection detectPpgFeet(List<double> ppg, double fs) {
  final x = orientPpg(ppg);
  final f = bandpass(x, fs, 0.5, math.min(8.0, 0.45 * fs));
  if (f.length < fs * 3) return BeatDetection.empty;

  // **The same correction on the finger, and it is not optional here either.** A PPG has a
  // dicrotic notch — the aortic valve closing, seen downstream — which is the same event that
  // doubles the chest count, arriving by a different route. Correcting only one stream would leave
  // the two rates disagreeing and fail the cross-sensor check instead, which is the same refusal
  // wearing a different reason.
  final spectral = spectralHr(hilbertEnvelope(f), fs);
  final detected = _detectPeaks(
    trace: f,
    fs: fs,
    prominence: 0.3 * std(f),
    spectralHrBpm: spectral,
  );
  final peaks = detected.peaks;
  if (peaks.length < 3) return BeatDetection.empty;

  final gaps = <double>[
    for (int i = 1; i < peaks.length; i++) (peaks[i] - peaks[i - 1]).toDouble(),
  ];
  final ibi = median(gaps);
  final win = math.min(0.25 * ibi, 0.20 * fs).toInt();

  final d = gradient(f);
  final feet = <double>[];
  for (final p in peaks) {
    final a = math.max(0, p - win);
    if (p - a < 3) continue;
    final seg = f.sublist(a, p + 1);
    final dseg = d.sublist(a, p + 1);

    int iMin = 0;
    for (int i = 1; i < seg.length; i++) {
      if (seg[i] < seg[iMin]) iMin = i;
    }
    if (p - (a + iMin) < 2) continue;

    int iSlope = iMin;
    for (int i = iMin; i < dseg.length; i++) {
      if (dseg[i] > dseg[iSlope]) iSlope = i;
    }
    final slope = dseg[iSlope];
    if (slope <= 1e-12) {
      feet.add((a + iMin) / fs);
      continue;
    }
    // baseline y = seg[iMin]; tangent y = seg[iSlope] + slope * (i - iSlope)
    double iFoot = iSlope + (seg[iMin] - seg[iSlope]) / slope;
    iFoot = iFoot.clamp(0, (p - a).toDouble());
    feet.add((a + iFoot) / fs);
  }

  final times = uniqueRounded(feet, 6);
  return BeatDetection(
    times: times,
    peakHr: _hrFromTimes(times),
    spectralHr: spectral,
    harmonicSuppressed: detected.suppressed,
  );
}

double _hrFromTimes(List<double> times) {
  final rr = <double>[
    for (int i = 1; i < times.length; i++)
      if (times[i] - times[i - 1] > 60.0 / maxBpm &&
          times[i] - times[i - 1] < 60.0 / 40.0)
        times[i] - times[i - 1],
  ];
  if (rr.isEmpty) return double.nan;
  return 60.0 / median(rr);
}

/// Match each SCG beat to the first unclaimed PPG foot inside the PTT window.
///
/// PTT is defined between two events of **the same cardiac cycle**. Pairing a beat with a foot
/// from a different cycle does not degrade the number, it invents one. So an unmatched beat is
/// dropped, never stretched to fit.
List<double> pairBeats(List<double> scgTimes, List<double> ppgTimes) {
  if (scgTimes.isEmpty || ppgTimes.isEmpty) return const [];
  final used = <int>{};
  final ptt = <double>[];
  for (final ts in scgTimes) {
    for (int i = 0; i < ppgTimes.length; i++) {
      if (used.contains(i)) continue;
      final t = ppgTimes[i];
      if (t >= ts + pttMinSeconds && t <= ts + pttMaxSeconds) {
        used.add(i);
        ptt.add((t - ts) * 1000.0);
        break; // earliest foot in the window
      }
    }
  }
  return ptt;
}

@immutable
class PttSummary {
  const PttSummary({
    required this.n,
    required this.median,
    required this.sd,
    required this.iqr,
    required this.pairYield,
  });

  final int n;
  final double median;
  final double sd;
  final double iqr;
  final double pairYield;
}

PttSummary summarise(List<double> pttMs, int nScgBeats) {
  if (pttMs.isEmpty) {
    return const PttSummary(
      n: 0,
      median: double.nan,
      sd: double.nan,
      iqr: double.nan,
      pairYield: 0.0,
    );
  }
  return PttSummary(
    n: pttMs.length,
    median: median(pttMs),
    // ddof=1 in the reference: a sample standard deviation, not a population one.
    sd: pttMs.length > 1 ? std(pttMs, ddof: 1) : double.nan,
    iqr: percentile(pttMs, 75) - percentile(pttMs, 25),
    pairYield: pttMs.length / math.max(nScgBeats, 1),
  );
}

/// Why the gate closed. Each maps onto a backend `rejection_reason`.
enum GateFailure {
  insufficientBeats,
  chestBeatDetectionUnreliable,
  fingerBeatDetectionUnreliable,
  sensorsDisagree,
  lowPairYield,
  pttTooVariable,
}

@immutable
class GateResult {
  const GateResult({required this.passed, this.failure, this.detail});

  final bool passed;
  final GateFailure? failure;

  /// Human-readable, for logs and the developer build. Never shown as a clinical statement.
  final String? detail;

  static const ok = GateResult(passed: true);
}

/// Four independent checks, cheapest first. Refuse rather than guess.
GateResult qualityGate({
  required double scgHr,
  required double scgSpectralHr,
  required double ppgHr,
  required double ppgSpectralHr,
  required PttSummary summary,
}) {
  if (summary.n < minPairs) {
    return GateResult(
      passed: false,
      failure: GateFailure.insufficientBeats,
      detail: 'only ${summary.n} paired beats, need $minPairs',
    );
  }

  for (final check in [
    ('chest', scgHr, scgSpectralHr, GateFailure.chestBeatDetectionUnreliable),
    ('finger', ppgHr, ppgSpectralHr, GateFailure.fingerBeatDetectionUnreliable),
  ]) {
    final (name, a, b, failure) = check;
    if (!a.isFinite || !b.isFinite) {
      return GateResult(
        passed: false,
        failure: failure,
        detail: '$name heart rate could not be estimated',
      );
    }
    // Before the agreement check, because two estimators agreeing on an impossible rate is a
    // detector describing itself, not a measurement. See [hrPlausibleMinBpm].
    if (a < hrPlausibleMinBpm || a > hrPlausibleMaxBpm) {
      return GateResult(
        passed: false,
        failure: failure,
        detail:
            '$name rate ${a.toStringAsFixed(1)} bpm is outside the seated plausible window '
            '${hrPlausibleMinBpm.toStringAsFixed(0)}-'
            '${hrPlausibleMaxBpm.toStringAsFixed(0)} bpm',
      );
    }
    // EC13 at this sensor's own peak-detected rate, as the reference does.
    final tol = hrToleranceBpm(a);
    if ((a - b).abs() > tol) {
      return GateResult(
        passed: false,
        failure: failure,
        detail:
            '$name beat detection unreliable: '
            'peak ${a.toStringAsFixed(1)} bpm vs spectral ${b.toStringAsFixed(1)} bpm '
            '= ${(a - b).abs().toStringAsFixed(1)} bpm apart, EC13 limit '
            '${tol.toStringAsFixed(1)} bpm at ${a.toStringAsFixed(0)} bpm',
      );
    }
  }

  // The strongest check, and the one a single-sensor product has no way to run: if the chest and
  // the finger disagree about the heart rate, they are not seeing the same heartbeats, so no
  // transit time exists between them.
  // EC13 at the *lower* of the two rates: the conservative reading, and the reference's.
  final crossTol = hrToleranceBpm(math.min(scgHr, ppgHr));
  if ((scgHr - ppgHr).abs() > crossTol) {
    return GateResult(
      passed: false,
      failure: GateFailure.sensorsDisagree,
      detail:
          'chest ${scgHr.toStringAsFixed(1)} bpm vs finger ${ppgHr.toStringAsFixed(1)} bpm '
          '= ${(scgHr - ppgHr).abs().toStringAsFixed(1)} bpm apart, EC13 limit '
          '${crossTol.toStringAsFixed(1)} bpm — not the same heartbeats',
    );
  }

  if (summary.pairYield < minPairYield) {
    return GateResult(
      passed: false,
      failure: GateFailure.lowPairYield,
      detail:
          'only ${(100 * summary.pairYield).toStringAsFixed(1)}% of beats paired, '
          'need ${(100 * minPairYield).toStringAsFixed(0)}%',
    );
  }

  if (summary.sd.isFinite && summary.sd > maxPttSdMs) {
    return GateResult(
      passed: false,
      failure: GateFailure.pttTooVariable,
      detail:
          'PTT spread ${summary.sd.toStringAsFixed(1)} ms, '
          'ceiling ${maxPttSdMs.toStringAsFixed(1)} ms',
    );
  }

  return GateResult.ok;
}

@immutable
class PttAnalysis {
  const PttAnalysis({
    required this.gate,
    required this.pttMs,
    required this.summary,
    required this.nScgBeats,
    required this.nPpgFeet,
    required this.scgHr,
    required this.ppgHr,
    required this.scgSpectralHr,
    required this.ppgSpectralHr,
    this.scgHarmonicSuppressed = false,
    this.ppgHarmonicSuppressed = false,
  });

  final GateResult gate;

  /// One interval per paired beat, milliseconds. Present whether or not the gate passed, so a
  /// caller can report the count; the *caller* decides whether they may be submitted.
  final List<double> pttMs;

  final PttSummary summary;
  final int nScgBeats;
  final int nPpgFeet;
  final double scgHr;
  final double ppgHr;
  final double scgSpectralHr;
  final double ppgSpectralHr;

  /// Whether either detector needed its second pass. Logged by the pipeline; never submitted.
  final bool scgHarmonicSuppressed;
  final bool ppgHarmonicSuppressed;
}

/// One capture in, one analysis out. The whole chain.
PttAnalysis analyseCapture({
  required List<double> scg,
  required double fsScg,
  required List<double> ppg,
  required double fsPpg,
}) {
  final scgBeats = detectScgBeats(scg, fsScg);
  final ppgFeet = detectPpgFeet(ppg, fsPpg);
  final pttMs = pairBeats(scgBeats.times, ppgFeet.times);
  final summary = summarise(pttMs, scgBeats.times.length);

  return PttAnalysis(
    gate: qualityGate(
      scgHr: scgBeats.peakHr,
      scgSpectralHr: scgBeats.spectralHr,
      ppgHr: ppgFeet.peakHr,
      ppgSpectralHr: ppgFeet.spectralHr,
      summary: summary,
    ),
    pttMs: pttMs,
    summary: summary,
    nScgBeats: scgBeats.times.length,
    nPpgFeet: ppgFeet.times.length,
    scgHr: scgBeats.peakHr,
    ppgHr: ppgFeet.peakHr,
    scgSpectralHr: scgBeats.spectralHr,
    ppgSpectralHr: ppgFeet.spectralHr,
    scgHarmonicSuppressed: scgBeats.harmonicSuppressed,
    ppgHarmonicSuppressed: ppgFeet.harmonicSuppressed,
  );
}
